### ISSUE TITLE
Layout issue when sharing - landscape

### ISSUE THREAD

**Issue by mythodeia** [mariohahn/MHVideoPhotoGallery#106]
steps to reproduce:
1. open app. Choose local
2. choose camera roll
3. tap to open a thumb
4. rotate to landscape
5. tap to share
there is an issue with the layout of the images

screenshot:
![screen](https://cloud.githubusercontent.com/assets/1748458/8057669/13979932-0ebc-11e5-8cde-726f505bf5d8.png)

**Comment by mythodeia** [comment]
am i the only one who has issues in landscape mode?

**Comment by hitendradeveloper** [comment]
I am facing the same issue. Looking for solution.

**Comment by mariohahn** [comment]
Is the issue still there?

**Comment by mythodeia** [comment]
@mariohahn hey i closed this since a lot of time has passed and did not get a response. Yeap the issue is still there if you follow the steps provided in my 1st comment.
Below is a screen from the iPhone X simulator
![screen](https://user-images.githubusercontent.com/1748458/35443001-1620e5ea-02b2-11e8-98a7-c2ce6b02222c.png)
