### ISSUE TITLE
loading MHGallery.bundle in Swift project 

### ISSUE THREAD

**Issue by inov** [mariohahn/MHVideoPhotoGallery#118]
I have included MHVideoPhotoGallery in a Swift project with cocoapods. The gallery is working except for one problem. 
When presenting the MHGalleryController the app crashes when it reaches this method  in MHGalleryImageViewerViewController:

``` 
-(void)updateTitleForIndex:(NSInteger)pageIndex{
    NSString *localizedString  = MHGalleryLocalizedString(@"imagedetail.title.current");
    self.navigationItem.title = [NSString stringWithFormat:localizedString,@(pageIndex+1),@(self.numberOfGalleryItems)];   
}
```

It turns out that the LocalizedString returns nil because the MHGallery.bundle file isn't correctly loaded.
Can someone explain to me how I can include the MHGallery.bundle file in my project?

Thanks

**Comment by violabg** [comment]
I have the same problem, how did you solve it?
