### ISSUE TITLE
Newbie question: use_frameworks + import?

### ISSUE THREAD

**Issue by netwire88** [mariohahn/MHVideoPhotoGallery#125]
Hi,
I was able to successfully import `MHVideoPhotoGallery` via Cocoapods. However, I am having trouble importing the files:
```
platform :ios, '8.0'
use_frameworks!
pod 'MHVideoPhotoGallery', '~> 2.0'
```

I have these code but it isn't working,
In the `Project-Bridging-Header.h` file, I have:
```
#import <MMHVideoPhotoGallery/MHGallery.h>
```
In the controllers, I also tried `import MHGallery` and that didn't work, Xcode complains `No such module 'MHGallery'`.

Any suggestions? Is there a Swift version of the example project?

**Comment by netwire88** [comment]
Ask help please?

**Comment by mariohahn** [comment]
First of all just use pod 'MHVideoPhotoGallery' without a Version, to always get the latest (: 

You don't need to use a Bridge Header just use "import MHVideoPhotoGallery" in your Swift ViewController.

**Comment by netwire88** [comment]
Worked wonders @mariohahn . Would it make sense to update the instructions on the GitHub?
