### ISSUE TITLE
whatsapp/instagram

### ISSUE THREAD

**Issue by syrakozz** [mariohahn/MHVideoPhotoGallery#79]
how i can share or add share via whatsapp or instagram

**Comment by mythodeia** [comment]
@syrakozz you need to include a separate UIActivity and include it in the source code to share with instagram. something like this perhaps: [here](https://github.com/coryalder/DMActivityInstagram)

**Comment by mariohahn** [comment]
You can also use the Default Activity ViewController and wait till they add their apps (extensions).

https://github.com/mariohahn/MHVideoPhotoGallery/blob/master/MHVideoPhotoGallery/MMHVideoPhotoGallery/MHCustomization/MHCustomization.h

showMHShareViewInsteadOfActivityViewController = NO // Default is YES

May they allow to add the ActivityController as ChildViewController on iOS 8, have tested it on iOS 7 and wasn't working.
