### ISSUE TITLE
Download URLS require authentication

### ISSUE THREAD

**Issue by mdaymond** [mariohahn/MHVideoPhotoGallery#84]
My videos and photos are on S3 with HTTP auth.   What is the best way for me to authenticate, so I can leverage your download/caching mechanism ?   Should I download and cache outside of your gallery ?

**Comment by mythodeia** [comment]
@mdaymond this library uses SDWebImage as a caching mechanism. So i think [this](http://www.mazdigital.com/blog/post/2014/using-sdwebimage-with-images-on-amazon-s3-a-brief-tutorial-from-maz/) might be of some assistance

**Comment by mdaymond** [comment]
Thanks.. got it.
