### ISSUE TITLE
Is file:/// protocol supported?

### ISSUE THREAD

**Issue by macpraveen** [mariohahn/MHVideoPhotoGallery#92]
I am trying to load images from local folder instead of http. But it does not seem to load. If this is not supported how can I implement this.

**Comment by mythodeia** [comment]
@macpraveen get all your folder images and create a MHGalleryItem using this:
``` + (instancetype)itemWithImage:(UIImage*)image; ```
then add all MHGalleryItems in an array and pass that array to the gallery instance.

**Comment by macpraveen** [comment]
Oh great. I will try it and let you know.

Thanks

**Comment by mariohahn** [comment]
i this case it would be better to use the delegate Methode - (MHGalleryItem*)itemForIndex:(NSInteger)index; instead of using the galleryItems Array...

**Comment by mythodeia** [comment]
@mariohahn :+1: thanks
