### ISSUE TITLE
Gallery Overview controller crashes on loading more than 200 images

### ISSUE THREAD

**Issue by macpraveen** [mariohahn/MHVideoPhotoGallery#93]
I am using gallery MHGalleryDataSource methods to load images in gallery. When there are more than 200 images the overview controller is unable to load and crashes. For small number of images it works fine. Also I tried to resize image dynamically to 100x100 and it works fine. Only the original size images fails to load in overview controller. 

All my images are local images.

Any solution?

**Comment by mythodeia** [comment]
on the overview controller you should use thumbnail sized images and not original size as this will most certainly crash the app.

**Comment by macpraveen** [comment]
It is not possible as both gallery controller and overview controller share the same datasource. How can I make gallery controller show original size images and overview controller to show thumbnails?

**Comment by mariohahn** [comment]
set the thumbnailURL in the GalleryItem

Gallery Overview prefers the MHImageTypeThumb

[self.thumbnail setImageForMHGalleryItem:galleryItem imageType:MHImageTypeThumb....
